#!/usr/bin/env bash
# =============================================================================
# run_priority.sh — prioritized experimental sweep for the advisor meeting.
#
# Three binary axes → 8 variants (NO thresholding, by request):
#   A. Fragmentation : rbrics (no fallback, no BPE)   vs  all_fallback_bpe
#   B. Labels        : original                       vs  synthetic GT rule
#   C. Normalization : none (no per-conv norm)         vs  l2
#
# Execution order (as requested):
#   for each VARIANT:
#       for each FOLD:
#           run vanilla → baselines → mose → gsat → motifsat
#
# So one fold trains the full model family set before moving to the next fold,
# and all folds of a variant finish before the next variant starts. This gives
# the advisor complete, comparable results for a variant as early as possible.
#
# SELF-CONTAINED: runs the full pipeline per variant, phase 1 → end:
#   phase 1  build vocabulary + rules.json (cascade / fallback / BPE), no threshold
#   phase 4  build synthetic-label GT cache  (synthetic-label variants only)
#   phase 5  train vanilla → baselines → mose → gsat → motifsat
# All three steps are idempotent — existing vocab / GT caches are reused, so the
# script is safe to re-run and resumes where it left off.
#
# Usage:
#   source experiment_config.sh
#   bash run_priority.sh                # all 8 variants, vocab→GT→train
#   VARIANTS_RUN="A1_B0_C1" bash run_priority.sh   # subset (space-separated keys)
#   FOLDS="0" BACKBONES="GIN" bash run_priority.sh # quick single-fold demo
#
# Requires (from experiment_config.sh): PROJECT DATA_ROOT VOCAB_ROOT OUT_ROOT
#   PROCESSED_ROOT (optional). The raw dataset folds must exist under DATA_ROOT;
#   vocabulary, rules, and GT caches are all generated by this script.
#   Tunables: RULE_RANK (default balanced), RULE_INDEX / RULE_INDEX_A0 /
#   RULE_INDEX_A1 (GT rule per fragmentation, default 0).
# =============================================================================
set -uo pipefail

PROJECT="${PROJECT:?set PROJECT (source experiment_config.sh)}"
DATA_ROOT="${DATA_ROOT:?set DATA_ROOT}"
VOCAB_ROOT="${VOCAB_ROOT:?set VOCAB_ROOT}"
OUT_ROOT="${OUT_ROOT:?set OUT_ROOT}"
PROCESSED_ROOT="${PROCESSED_ROOT:-$OUT_ROOT/processed}"

FOLDS="${FOLDS:-0 1 2 3 4}"
BACKBONES="${BACKBONES:-GIN GCN GAT SAGE PNA}"
DATASETS="${DATASETS:-Benzene BBBP Mutagenicity}"
NODE_ENCODER="${NODE_ENCODER:-onehot}"
EPOCHS="${EPOCHS:-150}"
# Rule ranking for rules.json (rule_index 0 = best). 'balanced' sorts by
# balance × separation × (1−spurious); 'pct1' by positive-class fraction.
RULE_RANK="${RULE_RANK:-balanced}"
# W&B stays offline-by-default (set WANDB_FLAGS="--use_wandb" to log; offline).
WANDB_FLAGS="${WANDB_FLAGS:-}"

# Rule index for synthetic-label (phase4) relabelling. The same index is used
# for both fragmentations; override per-fragmentation with RULE_INDEX_A0 /
# RULE_INDEX_A1 if the chosen GT rule differs between vocabularies.
RULE_INDEX="${RULE_INDEX:-0}"
RULE_INDEX_A0="${RULE_INDEX_A0:-$RULE_INDEX}"
RULE_INDEX_A1="${RULE_INDEX_A1:-$RULE_INDEX}"
GT_CACHE="$OUT_ROOT/gt_cache"   # shared root; apply_gt/--use_gt append {ds}/fold{f}/{variant}

# ── Axis definitions ─────────────────────────────────────────────────────────
# Fragmentation variant base names (must match built vocab dirs; NO _filter).
FRAG_A0="rbrics"            # rbrics, no fallback, no BPE
FRAG_A1="all_fallback_bpe"  # all + fallback + BPE

# The 8 variant keys: A{0,1}_B{0,1}_C{0,1}
ALL_KEYS="A0_B0_C0 A0_B0_C1 A0_B1_C0 A0_B1_C1 A1_B0_C0 A1_B0_C1 A1_B1_C0 A1_B1_C1"
VARIANTS_RUN="${VARIANTS_RUN:-$ALL_KEYS}"

frag_of()  { case "$1" in A0_*) echo "$FRAG_A0";; A1_*) echo "$FRAG_A1";; esac; }
labels_of(){ case "$1" in *_B0_*) echo "original";; *_B1_*) echo "synthetic";; esac; }
norm_of()  { case "$1" in *_C0) echo "none";; *_C1) echo "l2";; esac; }
rule_idx_of(){ case "$1" in A0_*) echo "$RULE_INDEX_A0";; A1_*) echo "$RULE_INDEX_A1";; esac; }

# Build the motif vocabulary + rules.json for one fragmentation (inline phase1),
# no thresholding. Idempotent: skips if the vocab dir + rules.json already
# exist for every dataset. Vocab is fold-agnostic (built at fold 0, reused).
#   A0 rbrics           → method=rbrics, no fallback, no BPE
#   A1 all_fallback_bpe → method=all, fallback, BPE
ensure_vocab() {
    local vv=$1 method fb bpe
    case "$vv" in
        "$FRAG_A0") method="rbrics"; fb=0; bpe=0 ;;
        "$FRAG_A1") method="all";    fb=1; bpe=1 ;;
        *) echo "   [error] unknown fragmentation '$vv'"; return 1 ;;
    esac
    echo "   [phase1] ensuring vocab for '$vv' (method=$method fallback=$fb bpe=$bpe)"
    for ds in $DATASETS; do
        if [ -f "$VOCAB_ROOT/$ds/$vv/rules.json" ]; then
            continue
        fi
        python3 "$PROJECT/MotifBreakdown/generate_vocab_rules.py" \
            --datasets "$ds" --data_root "$DATA_ROOT" \
            --out_dir "$VOCAB_ROOT" --method "$method" --variant "$vv" \
            $( [ "$fb"  = "1" ] && echo "--fallback" ) \
            $( [ "$bpe" = "1" ] && echo "--bpe" ) \
            --rule_rank "$RULE_RANK" --fold 0 \
          || { echo "   [error] generate_vocab_rules.py failed for $ds ($vv)"; return 1; }
    done
}

# Build the synthetic-label GT cache for one fragmentation (inline phase4), for
# every dataset × fold. Idempotent: skips a (ds,fold) whose relabel cache and
# the train split already exist. Requires rules.json (phase1) for the variant.
ensure_gt_cache() {
    local vv=$1 rule_idx=$2
    echo "   [phase4] ensuring GT cache for vocab=$vv rule_index=$rule_idx"
    for ds in $DATASETS; do
        for fold in $FOLDS; do
            local done_marker="$GT_CACHE/$ds/fold$fold/$vv/relabel1/train_with_gt.pt"
            if [ -f "$done_marker" ]; then
                continue
            fi
            python3 "$PROJECT/SharedModules/data/apply_gt.py" \
                --dataset "$ds" --fold "$fold" \
                --vocab_root "$VOCAB_ROOT" --variant "$vv" \
                --rule_index "$rule_idx" \
                --data_root "$DATA_ROOT" --out_dir "$GT_CACHE" \
              || { echo "   [error] apply_gt.py failed for $ds fold $fold ($vv)"; return 1; }
        done
    done
}

human_key() {
    echo "frag=$(frag_of "$1")  labels=$(labels_of "$1")  conv_normalize=$(norm_of "$1")"
}

# ── Per-family launchers (one fold, one variant) ─────────────────────────────
# $1 backbone  $2 dataset  $3 fold  $4 vocab_variant  $5 conv_normalize
#                                   $6 use_gt(0/1)     $7 gt_cache_dir

run_one_vanilla() {
    local bb=$1 ds=$2 fold=$3 vv=$4 cn=$5 use_gt=$6 gtc=$7 key=$8
    local gt_args=""
    [ "$use_gt" = "1" ] && gt_args="--use_gt --gt_cache $gtc"
    python3 "$PROJECT/SharedModules/baselines/run_vanilla.py" \
        --dataset "$ds" --fold "$fold" --backbone "$bb" \
        --node_encoder "$NODE_ENCODER" --epochs "$EPOCHS" \
        --conv_normalize "$cn" \
        --no_gnnexplainer --no_pgexplainer --no_mage \
        --data_root "$DATA_ROOT" --vocab_root "$VOCAB_ROOT" \
        --vocab_variant "$vv" --processed_root "$PROCESSED_ROOT" \
        --out_dir "$OUT_ROOT/$key/vanilla" $gt_args $WANDB_FLAGS
}

run_one_baselines() {
    # Post-hoc explainers loaded from the vanilla checkpoint just trained.
    # run_vanilla.py appends {dataset}/fold{fold}/{tag} to --load_weights_from,
    # so point it at the vanilla family root, NOT the per-dataset/fold dir.
    # When use_gt=1 the test graphs are GT-backed, so the explainers also get
    # GT-ROC, and the GT-trained vanilla checkpoint (gt tag) is the one loaded.
    local bb=$1 ds=$2 fold=$3 vv=$4 cn=$5 use_gt=$6 gtc=$7 key=$8
    local gt_args=""
    [ "$use_gt" = "1" ] && gt_args="--use_gt --gt_cache $gtc"
    python3 "$PROJECT/SharedModules/baselines/run_vanilla.py" \
        --dataset "$ds" --fold "$fold" --backbone "$bb" \
        --node_encoder "$NODE_ENCODER" --epochs 0 \
        --conv_normalize "$cn" \
        --load_weights_from "$OUT_ROOT/$key/vanilla" \
        --data_root "$DATA_ROOT" --vocab_root "$VOCAB_ROOT" \
        --vocab_variant "$vv" --processed_root "$PROCESSED_ROOT" \
        --out_dir "$OUT_ROOT/$key/baselines" $gt_args $WANDB_FLAGS
}

run_one_mose() {
    local bb=$1 ds=$2 fold=$3 vv=$4 cn=$5 use_gt=$6 gtc=$7 key=$8
    local gt_args=""
    [ "$use_gt" = "1" ] && gt_args="--use_gt --gt_cache $gtc"
    python3 "$PROJECT/MOSE-GNN/run.py" \
        --dataset "$ds" --fold "$fold" --backbone "$bb" \
        --node_encoder "$NODE_ENCODER" --w_feat --w_readout \
        --epochs "$EPOCHS" --conv_normalize "$cn" \
        --run_multi_explanation \
        --data_root "$DATA_ROOT" --vocab_root "$VOCAB_ROOT" \
        --vocab_variant "$vv" --processed_root "$PROCESSED_ROOT" \
        --out_dir "$OUT_ROOT/$key/mose" $gt_args $WANDB_FLAGS
}

run_one_gsat() {
    local bb=$1 ds=$2 fold=$3 vv=$4 cn=$5 key=$8
    python3 "$PROJECT/MotifSAT/run.py" \
        --dataset "$ds" --fold "$fold" --backbone "$bb" \
        --node_encoder "$NODE_ENCODER" --motif_method none \
        --learn_edge_att --noise node --info_loss_level node \
        --info_loss_coef 1.0 --epochs "$EPOCHS" --conv_normalize "$cn" \
        --data_root "$DATA_ROOT" --vocab_root "$VOCAB_ROOT" \
        --vocab_variant "$vv" --processed_root "$PROCESSED_ROOT" \
        --out_dir "$OUT_ROOT/$key/gsat" $WANDB_FLAGS
}

run_one_motifsat() {
    local bb=$1 ds=$2 fold=$3 vv=$4 cn=$5 use_gt=$6 gtc=$7 key=$8
    local gt_args=""
    [ "$use_gt" = "1" ] && gt_args="--use_gt --gt_cache $gtc"
    python3 "$PROJECT/MotifSAT/run.py" \
        --dataset "$ds" --fold "$fold" --backbone "$bb" \
        --node_encoder "$NODE_ENCODER" --motif_method readout \
        --noise none --info_loss_level none --info_loss_coef 0.0 \
        --w_feat --w_readout --w_message \
        --epochs "$EPOCHS" --conv_normalize "$cn" \
        --data_root "$DATA_ROOT" --vocab_root "$VOCAB_ROOT" \
        --vocab_variant "$vv" --processed_root "$PROCESSED_ROOT" \
        --out_dir "$OUT_ROOT/$key/motifsat" $gt_args $WANDB_FLAGS
}

# ── Main loop: VARIANT → FOLD → families ─────────────────────────────────────
echo "═══════════════════════════════════════════════════════════════════════"
echo " Priority sweep   datasets=[$DATASETS]  backbones=[$BACKBONES]  folds=[$FOLDS]"
echo " variants: $VARIANTS_RUN"
echo "═══════════════════════════════════════════════════════════════════════"

for key in $VARIANTS_RUN; do
    vv=$(frag_of "$key"); labels=$(labels_of "$key"); cn=$(norm_of "$key")
    use_gt=0; [ "$labels" = "synthetic" ] && use_gt=1

    echo ""
    echo "───────────────────────────────────────────────────────────────────────"
    echo " VARIANT $key   $(human_key "$key")   vocab_dir=$vv"
    echo "───────────────────────────────────────────────────────────────────────"

    # Build vocabulary + rules for this fragmentation first (inline phase1).
    # Idempotent and shared across all variants using the same fragmentation.
    if ! ensure_vocab "$vv"; then
        echo " [skip] could not build vocabulary for '$vv'. Skipping $key."
        continue
    fi

    # Synthetic-label variants: build the GT cache for this fragmentation
    # (inline phase4). If it can't be built, skip rather than train on missing
    # labels.
    if [ "$use_gt" = "1" ]; then
        if ! ensure_gt_cache "$vv" "$(rule_idx_of "$key")"; then
            echo " [skip] could not build GT cache for '$vv'. Skipping $key."
            continue
        fi
    fi

    for fold in $FOLDS; do
        for ds in $DATASETS; do
            for bb in $BACKBONES; do
                echo " [$key fold=$fold $ds $bb] vanilla → baselines → mose → gsat → motifsat"
                run_one_vanilla   "$bb" "$ds" "$fold" "$vv" "$cn" "$use_gt" "$GT_CACHE" "$key"
                run_one_baselines "$bb" "$ds" "$fold" "$vv" "$cn" "$use_gt" "$GT_CACHE" "$key"
                run_one_mose      "$bb" "$ds" "$fold" "$vv" "$cn" "$use_gt" "$GT_CACHE" "$key"
                run_one_gsat      "$bb" "$ds" "$fold" "$vv" "$cn" "" "" "$key"
                run_one_motifsat  "$bb" "$ds" "$fold" "$vv" "$cn" "$use_gt" "$GT_CACHE" "$key"
            done
        done
    done
done

echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo " Sweep complete. Collect + analyze:"
echo "   python3 $PROJECT/analysis/run_analysis.py all --out_root $OUT_ROOT --skip_regenerate"
echo "═══════════════════════════════════════════════════════════════════════"
