#!/usr/bin/env bash
# final_v1_env.sh — environment for the final_v1 experiment. SOURCE this before any
# stage/dispatch/worker script. Overrides experiment_config.sh defaults for a
# from-scratch build into final_v1/ (nothing reused from vocab_v2/results_v2).
#
#   Datasets : Mutagenicity, esol (LOWERCASE — canonical key), BBBP
#   Variants : base {rbrics, fg_first} → eval {rbrics, fg_first, rbrics_filter}
#   Backbones: GIN GCN SAGE GAT PNA        Folds: 0..4
#   GT       : DNF planted tiers (BBBP, Mutagenicity); esol regression = real only
#   Compute  : CPU-first, 1 core = 1 cell (FORCE_CPU=1, OMP pinned to 1)
set -uo pipefail
_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PROJECT="${PROJECT:-$(cd "$_HERE/.." && pwd)}"
# Base config (PROJECT, DATA_ROOT, NODE_ENCODER, EPOCHS, CONV_NORMALIZE, ...).
# shellcheck disable=SC1091
source "$PROJECT/experiment_config.sh"

# ── from-scratch roots ──
export OUT_ROOT="$PROJECT/final_v1"
export PROCESSED_ROOT="$PROJECT/processed_final_v1"
export VOCAB_ROOT="$PROJECT/vocab_final_v1"
export FINAL_TABLES="$OUT_ROOT/tables"
export FINAL_LOGS="$OUT_ROOT/logs"
export QUEUE_DIR="$OUT_ROOT/queue"
export CELL_TIMING_LOG="$FINAL_LOGS/cell_timing.tsv"

# ── scope ──
export DATASETS="Mutagenicity esol BBBP"
export DATASETS_CSV="Mutagenicity esol BBBP"
export DATASETS_SPECIAL=""
export BACKBONES="${BACKBONES:-GIN GCN SAGE GAT PNA}"
export FOLDS="${FOLDS:-0 1 2 3 4}"
export VOCAB_FOCUS="rbrics,fg_first"      # base variants; baselines add the *_filter eval
export CONV_NORMALIZE="none"
export NODE_ENCODER="onehot"
export EPOCHS="${EPOCHS:-500}"

# ── DNF GT planting (tiers auto-generated by phase4) ──
export RULE_ENGINE="dnf"
export RULE_TIERS="1"
export RULE_DNF_N="${RULE_DNF_N:-2}"
export RULE_DNF_ARMS="${RULE_DNF_ARMS:-balanced}"
export GT_ONLY="0"                         # keep the real-label tier too

# ── CPU-first, no throttling ──
export FORCE_CPU="1"
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1
export WANDB_MODE=disabled
export SKIP_EXISTING="${SKIP_EXISTING:-1}"  # idempotent resume: skip completed cells

# ── the 4 acquired 24h holders  "jobid:cores" (override HOLDERS to re-point) ──
export HOLDERS="${HOLDERS:-20774533:64 20774534:46 20774535:20 20774536:20}"

mkdir -p "$OUT_ROOT" "$FINAL_TABLES" "$FINAL_LOGS" "$QUEUE_DIR"
